apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: development
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-cont
        image: nginx:1.15.1
        ports:
        - containerPort: 80
        resources:         
          limits:          
            cpu: 50m        
            memory: "55Mi"
